FROM fluent/fluentd:latest

RUN apk add --no-cache --update --virtual .build-deps \
    sudo build-base ruby-dev \
&& sudo gem install fluent-plugin-elasticsearch \
&& sudo gem install fluent-plugin-kafka \
&& sudo gem sources --clear-all \
&& apk del .build-deps \
&& rm -rf /tmp/* /var/tmp* /usr/lib/ruby/gems/*/cache/*.gem
